version: 2

models:

    - name: sales
      description: One line by order - all columns and KPI related to sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
          
      columns:
          - name: orders_id
            description: orders id in combination with products id is the PK
            tests : 
            - not_null 

          - name: products_id
            tests :
            - not_null

          - name: qty

          - name: turnover
            tests :
            - not_null

          - name: purchase_cost
            tests :
            - not_null

          - name: margin
            description: turnover minus purchase costs